import { readdirSync, writeFileSync } from 'fs';
import { join, extname, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const publicDir = join(__dirname, '../public');
const outputFile = join(__dirname, '../src/heroImages.ts');
const exts = ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.svg', '.avif', '.bmp'];

const files = readdirSync(publicDir)
  .filter(f => exts.includes(extname(f).toLowerCase()))
  .map(f => `/${f}`);

const content = `// Auto-generated by scripts/generateHeroImages.ts\nexport const heroImages: string[] = ${JSON.stringify(files, null, 2)};\n`;

writeFileSync(outputFile, content);
console.log(`Generated ${outputFile} with ${files.length} images.`); 