// Auto-generated by scripts/generateHeroImages.ts
export const heroImages: string[] = [
  "/living2.jpg",
  "/livingroom1.jpg",
  "/pexels-christa-grover-977018-2121121 (1).jpg",
  "/pexels-expect-best-79873-323780.jpg",
  "/pexels-fotoaibe-1571453.jpg",
  "/pexels-itsterrymag-2631746 (1).jpg",
  "/pexels-luis-yanez-57302-206172.jpg",
  "/pexels-pixabay-261327.jpg"
];
